# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 052f0f4af3d56e9320e068e0d577cd12cff65ef94a63164392bfaa715c6e94bf0e9ad5cb7f6ad7e7d90edc2d7bcae0a003d9d520d36a6180a73981aa3e1298b4

test:
  secret_key_base: e950ad8a33b01a32f7ecbf5e13d33fe43e5a496877931bdf6d2cbf623a1fe23e8a2fba10f6f1fd3ebc04fe75caa770ef9bb02043cfae9d78d12b9c70b8cab007

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
